#ifndef DOS_SERVICES_CONSTANTS_H
#define DOS_SERVICES_CONSTANTS_H

#define DOS_SERVICE 0x21

#define DOS_ERROR 0FFFFh

// DOS SERVICES AH FOR 0x21
#define DOS_PROGRAM_TERMINATE								0 
#define DOS_KEYBOARD_INPUT_WITH_ECHO 
#define DOS_DISPLAY_OUTPUT 
#define DOS_WAIT_FOR_AUXILIARY_DEVICE_INPUT 
#define DOS_AUXILIARY_OUTPUT 
#define DOS_PRINTER_OUTPUT 
#define DOS_DIRECT_CONSOLE_IO 
#define DOS_WAIT_FOR_DIRECT_CONSOLE_INPUT_WITHOUT_ECHO 
#define DOS_WAIT_FOR_CONSOLE_INPUT_WITHOUT_ECHO 
#define DOS_PRINT_STRING 
#define DOS_BUFFERED_KEYBOARD_INPUT 
#define DOS_CHECK_STANDARD_INPUT_STATUS 
#define DOS_CLEAR_KEYBOARD_BUFFER  
#define DOS_DISK_RESET 
#define DOS_SELECT_DISK 
#define DOS_OPEN_FILE_USING_FCB 
#define DOS_CLOSE_FILE_USING_FCB 
#define DOS_SEARCH_FOR_FIRST_ENTRY_USING_FCB 
#define DOS_SEARCH_FOR_NEXT_ENTRY_USING_FCB 
#define DOS_DELETE_FILE_USING_FCB 
#define DOS_SEQUENTIAL_READ_USING_FCB 
#define DOS_SEQUENTIAL_WRITE_USING_FCB 
#define DOS_CREATEFILE_USING_FCB 
#define DOS_RENAME_FILE_USING_FCB 
#define DOS_DOS_DUMMY_FUNCTION_1   							// CP/M_NOT_USED/LISTED
#define DOS_GET_CURRENT_DEFAULT_DRIVE 
#define DOS_SET_DISK_TRANSFER_ADDRESS 
#define DOS_GET_ALLOCATION_TABLE_INFORMATION 
#define DOS_GET_ALLOCATION_TABLE_INFO_FOR_SPECIFIC_DEVICE 
#define DOS_DOS_DUMMY_FUNCTION_2   							// CP/M_NOT_USED/LISTED
#define DOS_DOS_DUMMY_FUNCTION_3							// CP/M_NOT_USED/LISTED
#define DOS_GET_POINTER_TO_DEFAULT_DRIVE_PARAMETER_TABLE 	// UNDOCUMENTED
#define DOS_DOS_DUMMY_FUNCTION_4   							// CP/M_NOT_USED/LISTED
#define DOS_RANDOM_READ_USING_FCB 
#define DOS_RANDOM_WRITE_USING_FCB 
#define DOS_GET_FILE_SIZE_USING_FCB 
#define DOS_SET_RELATIVE_RECORD_FIELD_FOR_FCB 
#define DOS_SET_INTERRUPT_VECTOR							25h
#define DOS_CREATE_NEW_PROGRAM_SEGMENT 
#define DOS_RANDOM_BLOCK_READ_USING_FCB 
#define DOS_RANDOM_BLOCK_WRITE_USING_FCB 
#define DOS_PARSE_FILENAME_FOR_FCB 
#define DOS_GET_DATE 
#define DOS_SET_DATE 
#define DOS_GET_TIME 
#define DOS_SET_TIME 
#define DOS_TOGGLE_VERIFY_SWITCH 
#define DOS_GET_DISK_TRANSFER_ADDRESS 
#define DOS_GET_DOS_VERSION_NUMBER 
#define DOS_TERMINATE_PROCESS_AND_REMAIN_RESIDENT 
#define DOS_GET_POINTER_TO_DRIVE_PARAMETER_TABLE			// UNDOCUMENTED
#define DOS_GET_SET_CTRL
#define DOS_GET_ADDRESS_TO_DOS_CRITICAL_FLAG				// UNDOCUMENTED
#define DOS_GET_INTERRUPT_VECTOR							35h
#define DOS_GET_DISK_FREE_SPACE								36h
#define DOS_GET_SET_SWITCH_CHARACTER						// UNDOCUMENTED
#define DOS_GET_SET_COUNTRY_DEPENDENT_INFORMATION 
#define DOS_CREATE_SUBDIRECTORY  
#define DOS_REMOVE_SUBDIRECTORY 
#define DOS_CHANGE_CURRENT_SUBDIRECTORY 
#define DOS_CREATE_FILE_USING_HANDLE						3Ch
#define DOS_OPEN_FILE_USING_HANDLE							3Dh	
#define DOS_CLOSE_FILE_USING_HANDLE							3Eh
#define DOS_READ_FILE_OR_DEVICE_USING_HANDLE				3Fh
#define DOS_WRITE_FILE_OR_DEVICE_USING_HANDLE				40h
#define DOS_DELETE_FILE										41h
#define DOS_MOVE_FILE_POINTER_USING_HANDLE					42h
#define DOS_CHANGE_FILE_MODE								43h
#define DOS_IO_CONTROL_FOR_DEVICES 
#define DOS_DUPLICATE_FILE_HANDLE 
#define DOS_FORCE_DUPLICATE_FILE_HANDLE 
#define DOS_GET_CURRENT_DIRECTORY 
#define DOS_ALLOCATE_MEMORY_BLOCKS							48h
#define DOS_FREE_ALLOCATED_MEMORY_BLOCKS					49h
#define DOS_MODIFY_ALLOCATED_MEMORY_BLOCKS 
#define DOS_EXEC_LOAD_AND_EXECUTE_PROGRAM 
#define DOS_TERMINATE_PROCESS_WITH_RETURN_CODE 
#define DOS_GET_RETURN_CODE_OF_SUB_PROCESS 
#define DOS_FIND_FIRST_MATCHING_FILE 
#define DOS_FIND_NEXT_MATCHING_FILE 
#define DOS_SET_CURRENT_PROCESS_ID   						// UNDOCUMENTED
#define DOS_GET_CURRENT_PROCESS_ID   						// UNDOCUMENTED
#define DOS_GET_POINTER_TO_DOS_INVARS						// UNDOCUMENTED
#define DOS_GENERATE_DRIVE_PARAMETER_TABLE  				// UNDOCUMENTED
#define DOS_GET_VERIFY_SETTING 
#define DOS_CREATE_PSP										// UNDOCUMENTED
#define DOS_RENAME_FILE 
#define DOS_GET_SET_FILE_DATE_AND_TIME_USING_HANDLE 
#define DOS_GET_SET_MEMORY_ALLOCATION_STRATEGY				// 3.X +   UNDOCUMENTED
#define DOS_GET_EXTENDED_ERROR_INFORMATION					59h				// 3.X + 
#define DOS_CREATE_TEMPORARY_FILE   						// 3.X + 
#define DOS_CREATE_NEW_FILE									// 3.X + 
#define DOS_LOCK_UNLOCK_FILE_ACCESS							// 3.X + 
#define DOS_CRITICAL_ERROR_INFORMATION						// UNDOCUMENTED
#define DOS_NETWORK_SERVICES								// 3.1 + 
#define DOS_NETWORK_REDIRECTION   							// 3.1 + 
#define DOS_GET_FULLY_QUALIFIED_FILE_NAME					// UNDOCUMENTED
#define DOS_GET_ADDRESS_OF_PROGRAM_SEGMENT_PREFIX			// 3.X + 
#define DOS_GET_SYSTEM_LEAD_BYTE_TABLE						// MSDOS_2.25_ONLY
#define DOS_SET_DEVICE_DRIVER_LOOK_AHEAD  					// UNDOCUMENTED
#define DOS_GET_EXTENDED_COUNTRY_INFORMATION				// 3.3 + 
#define DOS_GET_SET_GLOBAL_CODE_PAGE						// 3.3 + 
#define DOS_SET_HANDLE_COUNT								// 3.3 + 
#define DOS_FLUSH_BUFFER	 								// 3.3 + 
#define DOS_GET_SET_DISK_SERIAL_NUMBER						// UNDOCUMENTED

// SOFTWARE INTERRUPT NUMBERS
#define	IDIVIDE_BY_ZERO				0
#define	ISINGLE_STEP				1
#define INONMASKABLE				2
#define	IBREAKPOINT					3
#define	IOVERFLOW					4
#define IPRINT_SCREEN				5
#define	ISYSTEM_TIMER				8
#define IKEYBOARD					9
#define	IDISKETTE					14	
#define IVIDEO						16
#define IEQUIPMENT_DETERMINATION	17

#endif
