# CMAKE generated file: DO NOT EDIT!
# Generated by "Watcom WMake" Generator, CMake Version 3.31

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list


.ERASE

!ifndef VERBOSE
.SILENT
!endif

# A target that is always out of date.
cmake_force: .SYMBOLIC
cmake_force:
	@%null

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jeremythornton/dosbox/RETROLIB/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jeremythornton/dosbox/RETROLIB/bin

# Include any dependencies generated for this target.
!include CMakeFiles/test.dir/depend.make
# Include any dependencies generated by the compiler for this target.
!include CMakeFiles/test.dir/compiler_depend.make

# Include the progress variables for this target.
!include CMakeFiles/test.dir/progress.make

# Include the compile flags for this target's objects.
!include CMakeFiles/test.dir/flags.make

CMakeFiles/test.dir/codegen: .SYMBOLIC
CMakeFiles/test.dir/codegen:

CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_memory_size.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_memory_size.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_memory_size.c

CMakeFiles/test.dir/BIOS/bios_memory_size.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/BIOS/bios_memory_size.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_memory_size.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_memory_size.c

CMakeFiles/test.dir/BIOS/bios_memory_size.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/BIOS/bios_memory_size.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_timer_io_services.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_timer_io_services.c

CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_timer_io_services.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_timer_io_services.c

CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/BIOS/bios_video_services.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/BIOS/bios_video_services.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_video_services.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/test.dir/BIOS/bios_video_services.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_video_services.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_video_services.c

CMakeFiles/test.dir/BIOS/bios_video_services.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/BIOS/bios_video_services.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/BIOS/bios_video_services.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/BIOS/bios_video_services.c

CMakeFiles/test.dir/BIOS/bios_video_services.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/BIOS/bios_video_services.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/CGA/cga_detect_adapter.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/CGA/cga_detect_adapter.c

CMakeFiles/test.dir/CGA/cga_detect_adapter.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/CGA/cga_detect_adapter.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/CGA/cga_detect_adapter.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/CGA/cga_detect_adapter.c

CMakeFiles/test.dir/CGA/cga_detect_adapter.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/CGA/cga_detect_adapter.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DBG/debug_macros.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DBG/debug_macros.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DBG/debug_macros.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/test.dir/DBG/debug_macros.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DBG/debug_macros.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DBG/debug_macros.c

CMakeFiles/test.dir/DBG/debug_macros.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DBG/debug_macros.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DBG/debug_macros.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DBG/debug_macros.c

CMakeFiles/test.dir/DBG/debug_macros.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DBG/debug_macros.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_bresenham.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_bresenham.c

CMakeFiles/test.dir/DEMOS/demo_bresenham.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_bresenham.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_bresenham.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_bresenham.c

CMakeFiles/test.dir/DEMOS/demo_bresenham.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_bresenham.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_circles.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_circles.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_circles.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object CMakeFiles/test.dir/DEMOS/demo_circles.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_circles.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_circles.c

CMakeFiles/test.dir/DEMOS/demo_circles.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_circles.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_circles.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_circles.c

CMakeFiles/test.dir/DEMOS/demo_circles.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_circles.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_display_buffer.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_display_buffer.c

CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_display_buffer.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_display_buffer.c

CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_lines.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_lines.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_lines.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object CMakeFiles/test.dir/DEMOS/demo_lines.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_lines.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_lines.c

CMakeFiles/test.dir/DEMOS/demo_lines.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_lines.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_lines.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_lines.c

CMakeFiles/test.dir/DEMOS/demo_lines.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_lines.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_pixels.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_pixels.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_pixels.c

CMakeFiles/test.dir/DEMOS/demo_pixels.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_pixels.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_pixels.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_pixels.c

CMakeFiles/test.dir/DEMOS/demo_pixels.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_pixels.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_rectangles.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_rectangles.c

CMakeFiles/test.dir/DEMOS/demo_rectangles.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/demo_rectangles.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/demo_rectangles.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/demo_rectangles.c

CMakeFiles/test.dir/DEMOS/demo_rectangles.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/demo_rectangles.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DEMOS/pixelate.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DEMOS/pixelate.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/pixelate.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building C object CMakeFiles/test.dir/DEMOS/pixelate.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/pixelate.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/pixelate.c

CMakeFiles/test.dir/DEMOS/pixelate.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DEMOS/pixelate.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DEMOS/pixelate.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DEMOS/pixelate.c

CMakeFiles/test.dir/DEMOS/pixelate.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DEMOS/pixelate.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DOS/dos_services.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DOS/dos_services.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object CMakeFiles/test.dir/DOS/dos_services.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services.c

CMakeFiles/test.dir/DOS/dos_services.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DOS/dos_services.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services.c

CMakeFiles/test.dir/DOS/dos_services.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DOS/dos_services.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DOS/dos_services_3x.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DOS/dos_services_3x.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_3x.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object CMakeFiles/test.dir/DOS/dos_services_3x.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services_3x.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_3x.c

CMakeFiles/test.dir/DOS/dos_services_3x.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DOS/dos_services_3x.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services_3x.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_3x.c

CMakeFiles/test.dir/DOS/dos_services_3x.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DOS/dos_services_3x.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/DOS/dos_services_files.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/DOS/dos_services_files.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_files.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Building C object CMakeFiles/test.dir/DOS/dos_services_files.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services_files.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_files.c

CMakeFiles/test.dir/DOS/dos_services_files.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/DOS/dos_services_files.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/DOS/dos_services_files.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/DOS/dos_services_files.c

CMakeFiles/test.dir/DOS/dos_services_files.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/DOS/dos_services_files.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/EGA/ega_detect_adapter.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_16) "Building C object CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/EGA/ega_detect_adapter.c

CMakeFiles/test.dir/EGA/ega_detect_adapter.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/EGA/ega_detect_adapter.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/EGA/ega_detect_adapter.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/EGA/ega_detect_adapter.c

CMakeFiles/test.dir/EGA/ega_detect_adapter.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/EGA/ega_detect_adapter.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/FILE/file_tools.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/FILE/file_tools.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/FILE/file_tools.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_17) "Building C object CMakeFiles/test.dir/FILE/file_tools.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/FILE/file_tools.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/FILE/file_tools.c

CMakeFiles/test.dir/FILE/file_tools.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/FILE/file_tools.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/FILE/file_tools.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/FILE/file_tools.c

CMakeFiles/test.dir/FILE/file_tools.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/FILE/file_tools.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_18) "Building C object CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line.c

CMakeFiles/test.dir/HGA/hga_bresenham_line.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_bresenham_line.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_bresenham_line.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line.c

CMakeFiles/test.dir/HGA/hga_bresenham_line.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_bresenham_line.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line_naive.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_19) "Building C object CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line_naive.c

CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_bresenham_line_naive.c

CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_detect_adapter.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_20) "Building C object CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_detect_adapter.c

CMakeFiles/test.dir/HGA/hga_detect_adapter.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_detect_adapter.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_detect_adapter.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_detect_adapter.c

CMakeFiles/test.dir/HGA/hga_detect_adapter.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_detect_adapter.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_display_buffer.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_21) "Building C object CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_display_buffer.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_display_buffer.c

CMakeFiles/test.dir/HGA/hga_display_buffer.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_display_buffer.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_display_buffer.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_display_buffer.c

CMakeFiles/test.dir/HGA/hga_display_buffer.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_display_buffer.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_fast_line.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_fast_line.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_fast_line.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_22) "Building C object CMakeFiles/test.dir/HGA/hga_fast_line.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_fast_line.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_fast_line.c

CMakeFiles/test.dir/HGA/hga_fast_line.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_fast_line.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_fast_line.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_fast_line.c

CMakeFiles/test.dir/HGA/hga_fast_line.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_fast_line.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_filled_rectangle.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_23) "Building C object CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_filled_rectangle.c

CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_filled_rectangle.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_filled_rectangle.c

CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_jesko_circle.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_24) "Building C object CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_jesko_circle.c

CMakeFiles/test.dir/HGA/hga_jesko_circle.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_jesko_circle.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_jesko_circle.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_jesko_circle.c

CMakeFiles/test.dir/HGA/hga_jesko_circle.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_jesko_circle.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_pixel.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_pixel.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_pixel.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_25) "Building C object CMakeFiles/test.dir/HGA/hga_pixel.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_pixel.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_pixel.c

CMakeFiles/test.dir/HGA/hga_pixel.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_pixel.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_pixel.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_pixel.c

CMakeFiles/test.dir/HGA/hga_pixel.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_pixel.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_rectangle.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_rectangle.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_rectangle.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_26) "Building C object CMakeFiles/test.dir/HGA/hga_rectangle.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_rectangle.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_rectangle.c

CMakeFiles/test.dir/HGA/hga_rectangle.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_rectangle.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_rectangle.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_rectangle.c

CMakeFiles/test.dir/HGA/hga_rectangle.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_rectangle.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HGA/hga_video_mode.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HGA/hga_video_mode.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_video_mode.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_27) "Building C object CMakeFiles/test.dir/HGA/hga_video_mode.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_video_mode.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_video_mode.c

CMakeFiles/test.dir/HGA/hga_video_mode.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HGA/hga_video_mode.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HGA/hga_video_mode.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HGA/hga_video_mode.c

CMakeFiles/test.dir/HGA/hga_video_mode.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HGA/hga_video_mode.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_crtc.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_28) "Building C object CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HW/hw_detect_crtc.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_crtc.c

CMakeFiles/test.dir/HW/hw_detect_crtc.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HW/hw_detect_crtc.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HW/hw_detect_crtc.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_crtc.c

CMakeFiles/test.dir/HW/hw_detect_crtc.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HW/hw_detect_crtc.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_graphics_adapter.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_29) "Building C object CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_graphics_adapter.c

CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/HW/hw_detect_graphics_adapter.c

CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/MEM/mem_arena.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/MEM/mem_arena.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_arena.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_30) "Building C object CMakeFiles/test.dir/MEM/mem_arena.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/MEM/mem_arena.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_arena.c

CMakeFiles/test.dir/MEM/mem_arena.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/MEM/mem_arena.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/MEM/mem_arena.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_arena.c

CMakeFiles/test.dir/MEM/mem_arena.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/MEM/mem_arena.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/MEM/mem_tools.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/MEM/mem_tools.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_tools.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_31) "Building C object CMakeFiles/test.dir/MEM/mem_tools.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/MEM/mem_tools.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_tools.c

CMakeFiles/test.dir/MEM/mem_tools.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/MEM/mem_tools.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/MEM/mem_tools.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/MEM/mem_tools.c

CMakeFiles/test.dir/MEM/mem_tools.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/MEM/mem_tools.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/TEST/test_video_info.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/TEST/test_video_info.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/TEST/test_video_info.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_32) "Building C object CMakeFiles/test.dir/TEST/test_video_info.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/TEST/test_video_info.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/TEST/test_video_info.c

CMakeFiles/test.dir/TEST/test_video_info.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/TEST/test_video_info.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/TEST/test_video_info.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/TEST/test_video_info.c

CMakeFiles/test.dir/TEST/test_video_info.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/TEST/test_video_info.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/TIME/time_tools.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/TIME/time_tools.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/TIME/time_tools.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_33) "Building C object CMakeFiles/test.dir/TIME/time_tools.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/TIME/time_tools.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/TIME/time_tools.c

CMakeFiles/test.dir/TIME/time_tools.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/TIME/time_tools.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/TIME/time_tools.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/TIME/time_tools.c

CMakeFiles/test.dir/TIME/time_tools.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/TIME/time_tools.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/VGA/vga_detect_adapter.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_34) "Building C object CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/VGA/vga_detect_adapter.c

CMakeFiles/test.dir/VGA/vga_detect_adapter.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/VGA/vga_detect_adapter.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/VGA/vga_detect_adapter.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/VGA/vga_detect_adapter.c

CMakeFiles/test.dir/VGA/vga_detect_adapter.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/VGA/vga_detect_adapter.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

CMakeFiles/test.dir/main.c.obj: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/main.c.obj: /Users/jeremythornton/dosbox/RETROLIB/src/main.c
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_35) "Building C object CMakeFiles/test.dir/main.c.obj"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/main.c.obj -c -cc /Users/jeremythornton/dosbox/RETROLIB/src/main.c

CMakeFiles/test.dir/main.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/test.dir/main.c.i"
	/opt/watcom/armo64/wcl -zq -d+ $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -foCMakeFiles/test.dir/main.c.i -pl -cc /Users/jeremythornton/dosbox/RETROLIB/src/main.c

CMakeFiles/test.dir/main.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/test.dir/main.c.s"
	$(CMAKE_COMMAND) -E cmake_unimplemented_variable CMAKE_C_CREATE_ASSEMBLY_SOURCE

# Object files for target test
test_OBJECTS = &
"'CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj'" &
"'CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj'" &
"'CMakeFiles/test.dir/BIOS/bios_video_services.c.obj'" &
"'CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj'" &
"'CMakeFiles/test.dir/DBG/debug_macros.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_circles.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_lines.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj'" &
"'CMakeFiles/test.dir/DEMOS/pixelate.c.obj'" &
"'CMakeFiles/test.dir/DOS/dos_services.c.obj'" &
"'CMakeFiles/test.dir/DOS/dos_services_3x.c.obj'" &
"'CMakeFiles/test.dir/DOS/dos_services_files.c.obj'" &
"'CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj'" &
"'CMakeFiles/test.dir/FILE/file_tools.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_fast_line.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_pixel.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_rectangle.c.obj'" &
"'CMakeFiles/test.dir/HGA/hga_video_mode.c.obj'" &
"'CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj'" &
"'CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj'" &
"'CMakeFiles/test.dir/MEM/mem_arena.c.obj'" &
"'CMakeFiles/test.dir/MEM/mem_tools.c.obj'" &
"'CMakeFiles/test.dir/TEST/test_video_info.c.obj'" &
"'CMakeFiles/test.dir/TIME/time_tools.c.obj'" &
"'CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj'" &
"'CMakeFiles/test.dir/main.c.obj'"

# External object files for target test
test_EXTERNAL_OBJECTS =

test.exe: CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj
test.exe: CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj
test.exe: CMakeFiles/test.dir/BIOS/bios_video_services.c.obj
test.exe: CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj
test.exe: CMakeFiles/test.dir/DBG/debug_macros.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_circles.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_lines.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj
test.exe: CMakeFiles/test.dir/DEMOS/pixelate.c.obj
test.exe: CMakeFiles/test.dir/DOS/dos_services.c.obj
test.exe: CMakeFiles/test.dir/DOS/dos_services_3x.c.obj
test.exe: CMakeFiles/test.dir/DOS/dos_services_files.c.obj
test.exe: CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj
test.exe: CMakeFiles/test.dir/FILE/file_tools.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_fast_line.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_pixel.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_rectangle.c.obj
test.exe: CMakeFiles/test.dir/HGA/hga_video_mode.c.obj
test.exe: CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj
test.exe: CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj
test.exe: CMakeFiles/test.dir/MEM/mem_arena.c.obj
test.exe: CMakeFiles/test.dir/MEM/mem_tools.c.obj
test.exe: CMakeFiles/test.dir/TEST/test_video_info.c.obj
test.exe: CMakeFiles/test.dir/TIME/time_tools.c.obj
test.exe: CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj
test.exe: CMakeFiles/test.dir/main.c.obj
test.exe: CMakeFiles/test.dir/build.make
test.exe: CMakeFiles/test.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles --progress-num=$(CMAKE_PROGRESS_36) "Linking C executable test.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/test.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/test.dir/build: .SYMBOLIC
CMakeFiles/test.dir/build: test.exe

CMakeFiles/test.dir/clean: .SYMBOLIC
CMakeFiles/test.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/test.dir/cmake_clean.cmake

CMakeFiles/test.dir/depend: .SYMBOLIC
CMakeFiles/test.dir/depend:
	cd /Users/jeremythornton/dosbox/RETROLIB/bin && $(CMAKE_COMMAND) -E cmake_depends "Watcom WMake" /Users/jeremythornton/dosbox/RETROLIB/src /Users/jeremythornton/dosbox/RETROLIB/src /Users/jeremythornton/dosbox/RETROLIB/bin /Users/jeremythornton/dosbox/RETROLIB/bin /Users/jeremythornton/dosbox/RETROLIB/bin/CMakeFiles/test.dir/DependInfo.cmake "--color=$(COLOR)"

