file(REMOVE_RECURSE
  "CMakeFiles/test.dir/BIOS/bios_memory_size.c.obj"
  "CMakeFiles/test.dir/BIOS/bios_timer_io_services.c.obj"
  "CMakeFiles/test.dir/BIOS/bios_video_services.c.obj"
  "CMakeFiles/test.dir/CGA/cga_detect_adapter.c.obj"
  "CMakeFiles/test.dir/DBG/debug_macros.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_bresenham.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_circles.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_display_buffer.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_lines.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_pixels.c.obj"
  "CMakeFiles/test.dir/DEMOS/demo_rectangles.c.obj"
  "CMakeFiles/test.dir/DEMOS/pixelate.c.obj"
  "CMakeFiles/test.dir/DOS/dos_services.c.obj"
  "CMakeFiles/test.dir/DOS/dos_services_3x.c.obj"
  "CMakeFiles/test.dir/DOS/dos_services_files.c.obj"
  "CMakeFiles/test.dir/EGA/ega_detect_adapter.c.obj"
  "CMakeFiles/test.dir/FILE/file_tools.c.obj"
  "CMakeFiles/test.dir/HGA/hga_bresenham_line.c.obj"
  "CMakeFiles/test.dir/HGA/hga_bresenham_line_naive.c.obj"
  "CMakeFiles/test.dir/HGA/hga_detect_adapter.c.obj"
  "CMakeFiles/test.dir/HGA/hga_display_buffer.c.obj"
  "CMakeFiles/test.dir/HGA/hga_fast_line.c.obj"
  "CMakeFiles/test.dir/HGA/hga_filled_rectangle.c.obj"
  "CMakeFiles/test.dir/HGA/hga_jesko_circle.c.obj"
  "CMakeFiles/test.dir/HGA/hga_pixel.c.obj"
  "CMakeFiles/test.dir/HGA/hga_rectangle.c.obj"
  "CMakeFiles/test.dir/HGA/hga_video_mode.c.obj"
  "CMakeFiles/test.dir/HW/hw_detect_crtc.c.obj"
  "CMakeFiles/test.dir/HW/hw_detect_graphics_adapter.c.obj"
  "CMakeFiles/test.dir/MEM/mem_arena.c.obj"
  "CMakeFiles/test.dir/MEM/mem_tools.c.obj"
  "CMakeFiles/test.dir/TEST/test_video_info.c.obj"
  "CMakeFiles/test.dir/TIME/time_tools.c.obj"
  "CMakeFiles/test.dir/VGA/vga_detect_adapter.c.obj"
  "CMakeFiles/test.dir/main.c.obj"
  "test.exe"
  "test.lib"
  "test.pdb"
)

# Per-language clean rules from dependency scanning.
foreach(lang C)
  include(CMakeFiles/test.dir/cmake_clean_${lang}.cmake OPTIONAL)
endforeach()
