# CMAKE generated file: DO NOT EDIT!
# Generated by "Watcom WMake" Generator, CMake Version 3.31

# compile C with /opt/watcom/armo64/wcl
C_DEFINES = 

C_INCLUDES = -I"/opt/watcom/h"

C_FLAGS = -w3 -bt=dos -d2 -za99 -ml

