/*****************************************************************//**
 * \file   dos_services_constants.h
 * \brief  
 * \note   defined on an as needed basis 
 * \author ifkno
 * \date   October 2021
 *********************************************************************/
//#pragma once
#ifndef DOS_SERVICES_CONSTANTS_H
#define DOS_SERVICES_CONSTANTS_H

#define DOS_SERVICE 0x21

#define DOS_ERROR 0FFFFh

// DOS SERVICES AH FOR 0x21
#define PROGRAM_TERMINATE								0 
#define KEYBOARD_INPUT_WITH_ECHO 
#define DISPLAY_OUTPUT 
#define WAIT_FOR_AUXILIARY_DEVICE_INPUT 
#define AUXILIARY_OUTPUT 
#define PRINTER_OUTPUT 
#define DIRECT_CONSOLE_IO 
#define WAIT_FOR_DIRECT_CONSOLE_INPUT_WITHOUT_ECHO 
#define WAIT_FOR_CONSOLE_INPUT_WITHOUT_ECHO 
#define PRINT_STRING 
#define BUFFERED_KEYBOARD_INPUT 
#define CHECK_STANDARD_INPUT_STATUS 
#define CLEAR_KEYBOARD_BUFFER  
#define DISK_RESET 
#define SELECT_DISK 
#define OPEN_FILE_USING_FCB 
#define CLOSE_FILE_USING_FCB 
#define SEARCH_FOR_FIRST_ENTRY_USING_FCB 
#define SEARCH_FOR_NEXT_ENTRY_USING_FCB 
#define DELETE_FILE_USING_FCB 
#define SEQUENTIAL_READ_USING_FCB 
#define SEQUENTIAL_WRITE_USING_FCB 
#define CREATEFILE_USING_FCB 
#define RENAME_FILE_USING_FCB 
#define DOS_DUMMY_FUNCTION_1   							// CP/M_NOT_USED/LISTED
#define GET_CURRENT_DEFAULT_DRIVE 
#define SET_DISK_TRANSFER_ADDRESS 
#define GET_ALLOCATION_TABLE_INFORMATION 
#define GET_ALLOCATION_TABLE_INFO_FOR_SPECIFIC_DEVICE 
#define DOS_DUMMY_FUNCTION_2   							// CP/M_NOT_USED/LISTED
#define DOS_DUMMY_FUNCTION_3							// CP/M_NOT_USED/LISTED
#define GET_POINTER_TO_DEFAULT_DRIVE_PARAMETER_TABLE 	// UNDOCUMENTED
#define DOS_DUMMY_FUNCTION_4   							// CP/M_NOT_USED/LISTED
#define RANDOM_READ_USING_FCB 
#define RANDOM_WRITE_USING_FCB 
#define GET_FILE_SIZE_USING_FCB 
#define SET_RELATIVE_RECORD_FIELD_FOR_FCB 
#define SET_INTERRUPT_VECTOR							25h
#define CREATE_NEW_PROGRAM_SEGMENT 
#define RANDOM_BLOCK_READ_USING_FCB 
#define RANDOM_BLOCK_WRITE_USING_FCB 
#define PARSE_FILENAME_FOR_FCB 
#define GET_DATE 
#define SET_DATE 
#define GET_TIME 
#define SET_TIME 
#define TOGGLE_VERIFY_SWITCH 
#define GET_DISK_TRANSFER_ADDRESS 
#define GET_DOS_VERSION_NUMBER 
#define TERMINATE_PROCESS_AND_REMAIN_RESIDENT 
#define GET_POINTER_TO_DRIVE_PARAMETER_TABLE			// UNDOCUMENTED
#define GET_SET_CTRL
#define GET_ADDRESS_TO_DOS_CRITICAL_FLAG				// UNDOCUMENTED
#define GET_INTERRUPT_VECTOR							35h
#define GET_DISK_FREE_SPACE								36h
#define GET_SET_SWITCH_CHARACTER						// UNDOCUMENTED
#define GET_SET_COUNTRY_DEPENDENT_INFORMATION 
#define CREATE_SUBDIRECTORY  
#define REMOVE_SUBDIRECTORY 
#define CHANGE_CURRENT_SUBDIRECTORY 
#define CREATE_FILE_USING_HANDLE						3Ch
#define OPEN_FILE_USING_HANDLE							3Dh	
#define CLOSE_FILE_USING_HANDLE							3Eh
#define READ_FILE_OR_DEVICE_USING_HANDLE				3Fh
#define WRITE_FILE_OR_DEVICE_USING_HANDLE				40h
#define DELETE_FILE										41h
#define MOVE_FILE_POINTER_USING_HANDLE					42h
#define CHANGE_FILE_MODE								43h
#define IO_CONTROL_FOR_DEVICES 
#define DUPLICATE_FILE_HANDLE 
#define FORCE_DUPLICATE_FILE_HANDLE 
#define GET_CURRENT_DIRECTORY 
#define ALLOCATE_MEMORY_BLOCKS							48h
#define FREE_ALLOCATED_MEMORY_BLOCKS					49h
#define MODIFY_ALLOCATED_MEMORY_BLOCKS 
#define EXEC_LOAD_AND_EXECUTE_PROGRAM 
#define TERMINATE_PROCESS_WITH_RETURN_CODE 
#define GET_RETURN_CODE_OF_SUB_PROCESS 
#define FIND_FIRST_MATCHING_FILE 
#define FIND_NEXT_MATCHING_FILE 
#define SET_CURRENT_PROCESS_ID   						// UNDOCUMENTED
#define GET_CURRENT_PROCESS_ID   						// UNDOCUMENTED
#define GET_POINTER_TO_DOS_INVARS						// UNDOCUMENTED
#define GENERATE_DRIVE_PARAMETER_TABLE  				// UNDOCUMENTED
#define GET_VERIFY_SETTING 
#define CREATE_PSP										// UNDOCUMENTED
#define RENAME_FILE 
#define GET_SET_FILE_DATE_AND_TIME_USING_HANDLE 
#define GET_SET_MEMORY_ALLOCATION_STRATEGY				// 3.X +   UNDOCUMENTED
#define GET_EXTENDED_ERROR_INFORMATION					59h				// 3.X + 
#define CREATE_TEMPORARY_FILE   						// 3.X + 
#define CREATE_NEW_FILE									// 3.X + 
#define LOCK_UNLOCK_FILE_ACCESS							// 3.X + 
#define CRITICAL_ERROR_INFORMATION						// UNDOCUMENTED
#define NETWORK_SERVICES								// 3.1 + 
#define NETWORK_REDIRECTION   							// 3.1 + 
#define GET_FULLY_QUALIFIED_FILE_NAME					// UNDOCUMENTED
#define GET_ADDRESS_OF_PROGRAM_SEGMENT_PREFIX			// 3.X + 
#define GET_SYSTEM_LEAD_BYTE_TABLE						// MSDOS_2.25_ONLY
#define SET_DEVICE_DRIVER_LOOK_AHEAD  					// UNDOCUMENTED
#define GET_EXTENDED_COUNTRY_INFORMATION				// 3.3 + 
#define GET_SET_GLOBAL_CODE_PAGE						// 3.3 + 
#define SET_HANDLE_COUNT								// 3.3 + 
#define FLUSH_BUFFER	 								// 3.3 + 
#define GET_SET_DISK_SERIAL_NUMBER						// UNDOCUMENTED

// sOFTWARE INTERRUPT NUMBERS
#define	IDIVIDE_BY_ZERO				0
#define	ISINGLE_STEP				1
#define INONMASKABLE				2
#define	IBREAKPOINT					3
#define	IOVERFLOW					4
#define IPRINT_SCREEN				5
#define	ISYSTEM_TIMER				8
#define IKEYBOARD					9
#define	IDISKETTE					14	
#define IVIDEO						16
#define IEQUIPMENT_DETERMINATION	17


#endif