# CMAKE generated file: DO NOT EDIT!
# Generated by "Watcom WMake" Generator, CMake Version 3.31

# The generator used is:
set(CMAKE_DEPENDS_GENERATOR "Watcom WMake")

# The top level Makefile was generated from the following files:
set(CMAKE_MAKEFILE_DEPENDS
  "CMakeCache.txt"
  "CMakeFiles/3.31.0/CMakeCCompiler.cmake"
  "CMakeFiles/3.31.0/CMakeSystem.cmake"
  "/Users/jeremythornton/dosbox/RETROLIB/src/CMakeLists.txt"
  "/opt/homebrew/share/cmake/Modules/CMakeCInformation.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeCommonLanguageInclude.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeGenericSystem.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeInitializeConfigs.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeLanguageInformation.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake"
  "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake"
  "/opt/homebrew/share/cmake/Modules/Compiler/OpenWatcom-C.cmake"
  "/opt/homebrew/share/cmake/Modules/Compiler/OpenWatcom.cmake"
  "/opt/homebrew/share/cmake/Modules/Internal/CMakeCLinkerInformation.cmake"
  "/opt/homebrew/share/cmake/Modules/Internal/CMakeCommonLinkerInformation.cmake"
  "/opt/homebrew/share/cmake/Modules/Platform/DOS-Initialize.cmake"
  "/opt/homebrew/share/cmake/Modules/Platform/DOS-OpenWatcom-C.cmake"
  "/opt/homebrew/share/cmake/Modules/Platform/DOS-OpenWatcom.cmake"
  "/opt/homebrew/share/cmake/Modules/Platform/DOS.cmake"
  )

# The corresponding makefile is:
set(CMAKE_MAKEFILE_OUTPUTS
  "Makefile"
  "CMakeFiles/cmake.check_cache"
  )

# Byproducts of CMake generate step:
set(CMAKE_MAKEFILE_PRODUCTS
  "CMakeFiles/CMakeDirectoryInformation.cmake"
  )

# Dependency information for all targets:
set(CMAKE_DEPEND_INFO_FILES
  "CMakeFiles/test.dir/DependInfo.cmake"
  )
